### ISSUE TITLE
Publish on Drupal.org

### ISSUE THREAD

**Issue by patlc** [coralnexus/regstop#1]
Please, this is very useful.

**Comment by derekwebb** [comment]
Hi there, I was thinking about it but I found there is already a module there that has similar functionality | See the domain_registration module. 

I have plans for this little module though, and once I get it done it may be sufficiently different to post there. The change I have in mind is for a regsitration failure to add a cookie to the users' computer which would prevent them from trying other domains like gmail or whatever (for a period of time)... Not sure yet if that is needed. On an aside I have had no new spam signups since I started using this! Blocked 5 already since 2 days ago. 

What I found most odd is that Botcha and the like seemed to have no impact on the registration forms, whereas it blocks spam contacts like a charm... Go figure! Thanks for the feedback.

**Comment by derekwebb** [comment]
Closing this issue for now.
